name: "website-status-checker"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/website-status-checker
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
