name: "Deploy via SSH"

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.4
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to server
              env:
                  SERVER_IP: ${{ secrets.SERVER_IP }}
                  SSH_USER: ${{ secrets.SSH_USER }}
                  PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
              run: |
                  ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << EOF
                  echo "Current Directory:"
                  pwd
                  echo "Listing Directory Contents:"
                  ls -la
                  echo "Changing Directory:"
                  cd $PROJECT_PATH || exit
                  echo "Current Directory After cd:"
                  pwd
                  echo "Pulling Latest Code:"
                  git pull origin main
                  echo "Stopping Docker Containers:"
                  docker-compose down
                  echo "Starting Docker Containers:"
                  docker-compose up -d --build
                  EOF
